"""empty message

Revision ID: a9b55b22b841
Revises: bbe14c1b974a
Create Date: 2019-09-30 22:16:57.411703

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a9b55b22b841'
down_revision = 'bbe14c1b974a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('emprestimo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('idUsuario', sa.Integer(), nullable=True),
    sa.Column('idLivro', sa.Integer(), nullable=True),
    sa.Column('dataEmprestimo', sa.DateTime(), nullable=True),
    sa.Column('dataPrevista', sa.DateTime(), nullable=True),
    sa.Column('dataEfetiva', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['idLivro'], ['livros.id'], ),
    sa.ForeignKeyConstraint(['idUsuario'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('emprestimo')
    # ### end Alembic commands ###
