"""empty message

Revision ID: f0d70d91d43a
Revises: a9b55b22b841
Create Date: 2019-10-03 19:57:36.795415

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f0d70d91d43a'
down_revision = 'a9b55b22b841'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('emprestimos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_livro', sa.Integer(), nullable=True),
    sa.Column('id_usuario', sa.Integer(), nullable=True),
    sa.Column('data_emprestimo', sa.DateTime(), nullable=True),
    sa.Column('data_estimada', sa.DateTime(), nullable=True),
    sa.Column('data_devolucao', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_livro'], ['livros.id'], ),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('emprestimo')
    op.add_column('livros', sa.Column('status', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('livros', 'status')
    op.create_table('emprestimo',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('idUsuario', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('idLivro', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('dataEmprestimo', mysql.DATETIME(), nullable=True),
    sa.Column('dataPrevista', mysql.DATETIME(), nullable=True),
    sa.Column('dataEfetiva', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['idLivro'], ['livros.id'], name='emprestimo_ibfk_1'),
    sa.ForeignKeyConstraint(['idUsuario'], ['usuario.id'], name='emprestimo_ibfk_2'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('emprestimos')
    # ### end Alembic commands ###
